---
title: "Tidying data"
author: "Andrew Hicks"
date: "`r Sys.Date()`"
output: html_document
---

```{r knitr-options, include = FALSE}
knitr::opts_chunk$set(fig.align="center")
```

Priciples of tidy data:
- Observations as rows
- Variables as columns
- One type of observational units per table

Gather(data, key, value, ...): Gather columns into key-value pairs
- data: a data frame
- key: bare name of a new key column
- value: bare name of a new value column
```
# Look at wide_df
wide_df

# Gathering the columns of wide_df
gather(wide_df, my_key, my_val, -col)

```

Spead(data, key, value): Spread key-value pairs into columns
- data: a data frame
- key: bare name of column containing keys
- value: a bare name of column containing values
```
# Look at long_df
long_df

# Spread the key-value pairs of long_df
spread(long_df, my_key, my_val)

```

Seperate(data, col, into): Seperate one column into multiple
- data: a data frame
- col: bare name of column to seperate
- into: character vector of new column
```
# View the treatments data
treatments

# Seperate year_mo into two columns
seperate(treatments, year_mo, c("year", "month"))

```

Unite(data, col, ...): Unite multiple columns into one
- data: a data frame
- col: bare name of new column
- ...: bare names of columns to unite

```
# View treatments data
treatments

# Unite year and month to form year_mo column
unite(treatments, year_mo, year, month)
```

Practice:
```
# Apply gather() to bmi and save the result as bmi_long
bmi_long <- gather(bmi, bmi_val, year, -Country)

# View the first 20 rows of the result
head(bmi_long,20)

---

# Apply spread() to bmi_long
bmi_wide <- spread(bmi_long, year, bmi_val)

# View the head of bmi_wide
head(bmi_wide)
```

Other common symptoms:
- A single observational units is stored in multiple tables
- Multiple types of observational units are stored in the same table

Practice:
```
# Apply separate() to bmi_cc
bmi_cc_clean <- separate(bmi_cc, col = Country_ISO, into = c("Country", "ISO"), sep = "/")

# Print the head of the result
head(bmi_cc_clean)

---

# Apply unite() to bmi_cc_clean
bmi_cc <- unite(bmi_cc_clean, Country_ISO, Country, ISO, sep = "-")

# View the head of the result
head(bmi_cc)

---

# View the head of census
head(census)

# Gather the month columns
census2 <- gather(census, month, amount, -YEAR)

# Arrange rows by YEAR using dplyr's arrange
census2_arr <- arrange(census2, YEAR)

# View first 20 rows of census2_arr
head(census2_arr, 20)

---
# View first 50 rows of census_long
head(census_long, 50)

# Spread the type column
census_long2 <- spread(census_long, type, amount)

# View first 20 rows of census_long2
head(census_long2, 20)

---

# View the head of census_long3
head(census_long3)

# Separate the yr_month column into two
census_long4 <- separate(census_long3, yr_month, c("year", "month"))

# View the first 6 rows of the result
head(census_long4, 6)
```